# This is included for signaler development purposes.
signaler:
  build: .
  #image: jwilder/docker-gen
  environment:
    GENERATOR: self-signed
  volumes:
    # Mount docker socket to read events
    - /var/run/docker.sock:/tmp/docker.sock:ro
    # Mount test folder into container
    - ./data:/data
